AWSTemplateFormatVersion: 2010-09-09
Description: Pasi Demo Checkpoint3

Parameters:
  OmaNimi:
    Type: String
    Default: Pasi
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Resources:
  InstanceSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: PasinSecurityGroup
        GroupDescription: Security Group
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
          - FromPort: 80
            ToPort: 80
            IpProtocol: Tcp
            CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      InstanceType: t2.nano
      ImageId: !Ref LatestAmiId
      Tags:
        - Key: "Owner"
          Value: !Ref OmaNimi
      UserData:
        Fn::Base64:
          Fn::Join:
            - "\n"
            - - "#!/bin/bash"
              - "amazon-linux-extras install epel"
              - "amazon-linux-extras install nginx1"
              - "systemctl start nginx"

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: pasibucket
      Tags:
        - Key: "Owner"
          Value: !Ref OmaNimi

  Arn:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !GetAtt S3Bucket.Arn


Outputs:
  PublicDnsName:
    Description: DNS
    Value: !Ref EC2Instance
