AWSTemplateFormatVersion: 2010-09-09
Description: academy Demo CloudFormation

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
        BucketName: pasi-bucket2712

  SqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: pasi-jono-1

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      InstanceType: t2.micro
      ImageId: !Ref LatestAmiId
      Tags:
        - Key: "Name"
          Value: "pasi-ec2"

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: secu-gruuppi
      GroupName: pasi-security-group2
      VpcId: vpc-bc8f6cc1
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - subnet-2f0cdc70
        - subnet-94bf68f2
      SecurityGroups:
        - !Ref ALBSecurityGroup

#  Listeners:
    #          InstancePort: '80'
    #          Protocol: HTTP

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB Security group
      GroupName: pasi-security-group3
      VpcId: vpc-bc8f6cc1
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: PasiTarget
      Port: 80
      Protocol: HTTP
      VpcId: vpc-bc8f6cc1

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer