AWSTemplateFormatVersion: 2010-09-09
Description: academy Demo CloudFormation

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
        BucketName: pasi-bucket2712

  SqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: pasi-jono-1

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: secu-gruuppi
      GroupName: pasi-security-group2
      VpcId: vpc-bc8f6cc1
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - subnet-2f0cdc70
        - subnet-94bf68f2
      SecurityGroups:
        - !Ref ALBSecurityGroup

#  Listeners:
    #          InstancePort: '80'
    #          Protocol: HTTP

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB Security group
      GroupName: pasi-security-group3
      VpcId: vpc-bc8f6cc1
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: PasiTarget
      Port: 80
      Protocol: HTTP
      VpcId: vpc-bc8f6cc1

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref LaunchConfiguration
      AutoScalingGroupName: PasiAutoScalingGroup
      MaxSize: 4
      MinSize: 1
      VPCZoneIdentifier:
        - subnet-2f0cdc70
        - subnet-94bf68f2
      TargetGroupARNs:
        - !Ref TargetGroup

  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      UserData:
        Fn::Base64:
          Fn::Join:
            - "\n"
            - - "#!/bin/bash"
              - "amazon-linux-extras install epel"
              - "amazon-linux-extras install nginx1"
              - "systemctl start nginx"
      SecurityGroups:
        - Ref: InstanceSecurityGroup
        - sg-050c15cb06e5affb0
      LaunchConfigurationName: pasi-asg-lc
      ImageId: ami-08f3d892de259504d
      InstanceType: t2.micro